### ISSUE TITLE
[Feature request] Right click on crafting window to fetch items?

### ISSUE THREAD

**Issue by luojiesi** [hetima/DSP_Replenishment#4]
Hi, thanks for this mod. It was a must-have for me. The only issue I had was that it only supported a limited set of items since it only works with the building tool. Is it possible to make right clicks work on the crafting window as well? That I can fetch everything that I stored. Thanks!

**Comment by hetima** [comment]
implemented in 1.1.0
thanks

**Comment by luojiesi** [comment]
wow. thanks a lot for the fast action!
